name: learner_space_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.1
  dio: ^5.9.0
  provider: ^6.1.5+1
  flutter_secure_storage: ^9.2.4
  flutter_markdown: ^0.7.7+1
  intl: ^0.20.2
  lucide_icons: ^0.257.0
  jwt_decoder: ^2.0.1
  shimmer: ^3.0.0
  pdfx: ^2.9.2
  http: ^1.6.0

# -----------------------------
# ðŸš€ App Icon Configuration
# -----------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/Images/AppIcon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/User/
    - assets/Fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/Fonts/Poppins-Regular.ttf
        - asset: assets/Fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/Fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/Fonts/Poppins-Black.ttf
          weight: 900
